Update ruff.yml

diff --git a/.github/workflows/ruff.yml b/.github/workflows/ruff.yml
--- a/.github/workflows/ruff.yml
+++ b/.github/workflows/ruff.yml
@@ -20,3 +20,9 @@ jobs:
     - name: Analysing the code with ruff
       run: |
         ruff check $(git ls-files '*.py')
+    - name: Check linting results
+      run: |
+          if [[ $? -ne 0 ]]; then
+            echo "Linting errors found. PR cannot be merged."
+            exit 1
+          fi
